---
# Some modules have their package.json changed during installation.
- name: Module path exists
  stat:
    path: "{{ mm_root }}/modules/{{ item.name }}"
  register: register_module_path

- name: "Restore changes to {{ item.name }} if necessary"
  ansible.builtin.shell:
    cmd: git reset --hard --quiet
    chdir: "{{ mm_root }}/modules/{{ item.name }}"
  when: register_module_path.stat.exists

- name: "Download Module {{ item.name }}"
  ansible.builtin.git:
    repo: "{{ item.github }}"
    dest: "{{ mm_root }}/modules/{{ item.name }}"
    clone: yes
    force: yes
    update: yes

- name: "NPM Install Module {{ item.name }}"
  ansible.builtin.npm:
    path: "{{ mm_root }}/modules/{{ item.name }}"
  ignore_errors: yes
