---

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install Mirror
  ansible.builtin.include_tasks: install_magic_mirror.yml
  tags:
  - install

- name: Magic Mirror installed
  ansible.builtin.stat:
    path: /home/pi/MagicMirror
  register: magic_mirror_normal
  tags:
  - install
  - upgrade

- name: Magic Mirror docker installed
  ansible.builtin.stat:
    path: /home/pi/magicmirror
  register: magic_mirror_docker

# From https://github.com/sdetweil/MagicMirror_scripts#upgrade-to-next-magicmirror-version-from-an-existing-installation
- name: Upgrade normal Magic Mirror install
  ansible.builtin.shell: |
    bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)" apply
  when: magic_mirror_normal.stat.exists
  tags:
  - upgrade

- name: Magic Mirror Config.js
  ansible.builtin.template:
    src: './templates/config.js.j2'
    dest: "{{ mm_root }}/config/config.js"
  tags:
  - configuration

- name: Install Modules
  ansible.builtin.include_tasks: install_module.yml
  when: item.github is defined
  with_items: "{{ mm_modules }}"
  tags:
  - configuration
  - upgrade

- name: Copy files
  ansible.builtin.include_tasks: copy_files.yml
  when: item.src is defined
  with_items: "{{ mm_copy }}"
  tags:
  - configuration

- name: Restart install with new config
  ansible.builtin.shell: |
    pm2 restart MagicMirror
  tags:
  - configuration
  - reload
  - upgrade
