---

- name: Install software
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nodejs
    - npm

- name: Magic Mirror Config.js
  ansible.builtin.template:
    src: './templates/config.js.j2'
    dest: "{{ mm_root }}/config/config.js"

- name: Install Modules
  ansible.builtin.include_tasks: install_module.yml
  when: item.github is defined
  with_items: "{{ mm_modules }}"

- name: Copy images
  ansible.builtin.include_tasks: copy_files.yml
  when: item.src is defined
  with_items: "{{ mm_copy }}"

- name: Restart install with new config
  ansible.builtin.shell: |
    pm2 restart MagicMirror
