---

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Magic Mirror installed
  ansible.builtin.stat:
    path: /home/pi/MagicMirror
  register: magic_mirror_normal

- name: Magic Mirror docker installed
  ansible.builtin.stat:
    path: /home/pi/magicmirror
  register: magic_mirror_docker

- name: Install Magic Mirror
  ansible.builtin.shell: |
    # From https://github.com/sdetweil/MagicMirror_scripts.
    bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/raspberry.sh) --yes"
  when: not magic_mirror_normal.stat.exists and not magic_mirror_docker.stat.exists

- name: Turn off screen saver
  ansible.builtin.shell: |
    bash -c "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/screensaveroff.sh)"

- name: Boot with pm2
  ansible.builtin.shell: |
    # Use pm2 to autostart MagicMirror at bootup.
    bash -c "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/fixuppm2.sh)"

# From https://docs.magicmirror.builders/getting-started/upgrade-guide.html
- name: Upgrade normal Magic Mirror install
  ansible.builtin.shell: |
    cd MagicMirror
    git reset --hard --quiet
    git pull
    npm run install-mm
  when: magic_mirror_normal.stat.exists

- name: Install node packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nodejs
    - npm

- name: Magic Mirror Config.js
  ansible.builtin.template:
    src: './templates/config.js.j2'
    dest: "{{ mm_root }}/config/config.js"

- name: Install Modules
  ansible.builtin.include_tasks: install_module.yml
  when: item.github is defined
  with_items: "{{ mm_modules }}"

- name: Copy images
  ansible.builtin.include_tasks: copy_files.yml
  when: item.src is defined
  with_items: "{{ mm_copy }}"

- name: Restart install with new config
  ansible.builtin.shell: |
    pm2 restart MagicMirror
